In [22]:
#this is to include the library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import queue
import heapq

In [23]:
class grid :
    def __init__ (self):
        n = int (input("Enter the dimension of the grid"))
        self.dimension = n
        self.mat = np.zeros((self.dimension , self.dimension))
        
        #taking the matrix as the input
        print("Enter the matrix : " )
        for i in range(self.dimension):
            temp = input().strip().split()
            for j , x in zip(range(self.dimension) , temp):
                self.mat[i , j] = x;
        
        #Enter the start configuration
        temp = input("Enter the start configuration : " ).strip().split()
        self.current = (int(temp[0]),int (temp[1]))
        
        #Enter the final configuration
        temp = input("Enter the final configuration : " ).strip().split()
        self.final = (int (temp[0]) , int(temp[1]) )
        
    
    def left (self):
        if (self.current[1] == 0 or self.mat[self.current[0] , self.current[1] - 1] == 1):
            return False
        else:
            self.current[1] = self.current[1] - 1
            return True
    
    def right (self) :
        if (self.current[1] == self.dimension - 1  or self.mat[self.current[0] , self.current[1] + 1] == 1):
            return False
        else:
            self.current[1] = self.current[1] + 1
            return True
        
    def up (self):
        if (self.current[0] == 0 or self.mat[self.current[0] - 1 , self.current[1]] == 1):
            return False
        else:
            self.current[0] = self.current[0] - 1
            return True
    
    def down (self):
        if (self.current[0] == self.dimension - 1 or self.mat[self.current[0] + 1 , self.current[1]] == 1):
            return False
        else:
            self.current[0] = self.current[0] + 1
            return True

In [46]:
env = grid()

Enter the dimension of the grid6
Enter the matrix : 
0 1 0 0 1 0
0 1 0 1 0 0
0 0 1 1 1 0
1 0 0 1 0 0
1 1 0 1 1 0
0 0 0 0 0 0
Enter the start configuration : 0 0
Enter the final configuration : 0 5


In [47]:
def isValid (x , y):
    if (x >= 0 and x < env.dimension and y >= 0 and y < env.dimension ):
        return True
    return False


In [48]:
def BFS():
    start = env.current              #this is to store the current state
    goal = env.final
    grid = env.mat                     #this is to store the matrix
    
    print(start)
    print(goal)
    print(grid)
    
    d = {}                             #this is the dictionary that we are going to use
                                       #first element is the parent
                                       #second element is the action
            
    visited = set()                    #this is to mark the set of visited states
    
    q = queue.Queue()                  #this is to store the queue
    
    #initialise all the parameters
    d[start] = ((-1, -1) , "-1")
    q.put(start)
    
    ans = False                         #this is to keep track wether the solution is found or not
    counter = 0
    while not q.empty() and ans == False:
        counter += 1
        print("Number of steps :", counter)
        current = q.get()
        x = current[0]
        y = current[1]
        if (current == goal):
            ans = True
            break
        
        #print(current)
        if (isValid(x , y-1) and not grid[x][y-1] == 1 and (x , y-1) not in visited ):
            visited.add((x , y-1))
            d[(x , y-1)] = (current , "left")
            q.put((x , y-1))
        
        if (isValid(x , y+1) and not grid[x][y+1] == 1 and (x, y+1) not in visited):
            visited.add ((x , y+1))
            d[(x , y+1)] = (current , "right")
            q.put((x , y+1))
            
        if (isValid(x-1 , y) and not grid[x-1][y] == 1 and (x-1, y) not in visited):
            visited.add ((x-1 , y))
            d[(x-1 , y)] = (current , "up")
            q.put((x-1 , y))
        
        if (isValid(x+1 , y) and not grid[x+1][y] == 1 and (x+1, y) not in visited):
            visited.add ((x+1 , y))
            d[(x+1, y)] = ( current , "down")
            q.put((x+1 , y))
            
    
    #this is to print the path
    if (ans == False):
        print("Solution not found")
        return 
    

    path = []
    path_name = []
    current = goal
    #print(d)
    #print(d[current])
    
    
    while (not current == start):
        path.insert(0 , current)
        path_name.insert(0 , d[current][1])
        current = d[current][0]
        
    
    path.insert(0 , start)    
    for i , j in zip(path , path_name):
        print(i , j)
        
    print(goal)
    
    

In [49]:
BFS()

(0, 0)
(0, 5)
[[0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0.]
 [1. 0. 0. 1. 0. 0.]
 [1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
Number of steps : 1
Number of steps : 2
Number of steps : 3
Number of steps : 4
Number of steps : 5
Number of steps : 6
Number of steps : 7
Number of steps : 8
Number of steps : 9
Number of steps : 10
Number of steps : 11
Number of steps : 12
Number of steps : 13
Number of steps : 14
Number of steps : 15
Number of steps : 16
Number of steps : 17
Number of steps : 18
Number of steps : 19
Number of steps : 20
Number of steps : 21
(0, 0) down
(1, 0) down
(2, 0) right
(2, 1) down
(3, 1) right
(3, 2) down
(4, 2) down
(5, 2) right
(5, 3) right
(5, 4) right
(5, 5) up
(4, 5) up
(3, 5) up
(2, 5) up
(1, 5) up
(0, 5)


In [50]:
#using the heuristic
import heapq
def h_manhattan (x , y , x2 , y2):
    return abs (x2 - x) + abs (y2 - y)


In [51]:
def heuristic():
    start = env.current              #this is to store the current state
    goal = env.final
    grid = env.mat                     #this is to store the matrix
    
    print(start)
    print(goal)
    print(grid)
    
    d = {}                             #this is the dictionary that we are going to use
                                       #first element is the parent
                                       #second element is the action
                                       #third is the distance (cost till now)
                                       #fourth is the heuristic
            
    explored = set()                    #this is to mark the set of visited states
    
    counter_queue = 0
    q = []                             #this is to store the queue
    heapq.heapify(q)
    #initialise all the parameters
    d[start] = ((-1, -1) , "-1" , 0 , h_manhattan(start[0] , start[1] , goal[0] , goal[1]))
    heapq.heappush(q , (d[start][2] + d[start][3] , counter_queue , start))
    
    ans = False                         #this is to keep track wether the solution is found or not
    counter = 0
    while len(q) > 0 and ans == False:
        print("Number of steps :", counter)
        #print(q)
        dist , waste , current = heapq.heappop(q)
        #print(current)
        x = current[0]
        y = current[1]
        if (current == goal):
            ans = True
            break
        
        #print(counter , current)
        temp = d[current][2] + d[current][3]
        if (dist > temp):
            continue
        
        explored.add((current))
        counter+=1
        #print(current)
        if (isValid(x , y-1) and not grid[x][y-1] == 1 and (x , y-1) not in explored ):
            d[(x , y-1)] = (current , "left" , d[current][2] + 1, h_manhattan(x , y-1 , goal[0] , goal[1]))
            counter_queue += 1
            heapq.heappush(q , (d[(x,y-1)][2] + d[(x , y-1)][3] , counter_queue , (x , y-1)))
            
        if (isValid(x , y+1) and not grid[x][y+1] == 1 and (x , y+1) not in explored ):
            d[(x , y+1)] = (current , "right" , d[current][2] + 1, h_manhattan(x , y+1 , goal[0] , goal[1]))
            counter_queue += 1
            heapq.heappush(q , (d[(x,y+1)][2] + d[(x , y+1)][3] , counter_queue , (x , y+1)))
        
        if (isValid(x-1 , y) and not grid[x-1][y] == 1 and (x-1 , y) not in explored ):
            d[(x-1 , y)] = (current , "up" , d[current][2] + 1, h_manhattan(x-1 , y , goal[0] , goal[1]))
            counter_queue += 1
            heapq.heappush(q , (d[(x-1,y)][2] + d[(x-1 , y)][3] , counter_queue , (x-1 , y)))
        
        if (isValid(x+1 , y) and not grid[x+1][y] == 1 and (x+1 , y) not in explored ):
            d[(x+1 , y)] = (current , "down" , d[current][2] + 1, h_manhattan(x+1 , y , goal[0] , goal[1]))
            counter_queue += 1
            heapq.heappush(q , (d[(x+1,y)][2] + d[(x+1 , y)][3] , counter_queue , (x+1 , y)))
            
            
                 
    
    #this is to print the path
    if (ans == False):
        print("Solution not found")
        return 
    

    path = []
    path_name = []
    current = goal
    #print(d)
    #print(d[current])
    
    
    while (not current == start):
        path.insert(0 , current)
        path_name.insert(0 , d[current][1])
        current = d[current][0]
        
    
    path.insert(0 , start)    
    for i , j in zip(path , path_name):
        print(i , j)
        
    print(goal)
    
    

In [56]:
heuristic()

(0, 0)
(0, 5)
[[0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0.]
 [1. 0. 0. 1. 0. 0.]
 [1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
Number of steps : 0
Number of steps : 1
Number of steps : 2
Number of steps : 3
Number of steps : 4
Number of steps : 5
Number of steps : 6
Number of steps : 7
Number of steps : 8
Number of steps : 9
Number of steps : 10
Number of steps : 11
Number of steps : 12
Number of steps : 13
Number of steps : 14
Number of steps : 15
(0, 0) down
(1, 0) down
(2, 0) right
(2, 1) down
(3, 1) right
(3, 2) down
(4, 2) down
(5, 2) right
(5, 3) right
(5, 4) right
(5, 5) up
(4, 5) up
(3, 5) up
(2, 5) up
(1, 5) up
(0, 5)


In [53]:
import math
def h_euclidean(x , y , x2 , y2):
    return math.sqrt((x2 - x)**2 + (y2 - y)**2)

In [54]:
def heuristic2():
    start = env.current              #this is to store the current state
    goal = env.final
    grid = env.mat                     #this is to store the matrix
    
    print(start)
    print(goal)
    print(grid)
    
    d = {}                             #this is the dictionary that we are going to use
                                       #first element is the parent
                                       #second element is the action
                                       #third is the distance (cost till now)
                                       #fourth is the heuristic
            
    explored = set()                    #this is to mark the set of visited states
    
    counter_queue = 0
    q = []                             #this is to store the queue
    heapq.heapify(q)
    #initialise all the parameters
    d[start] = ((-1, -1) , "-1" , 0 , h_euclidean(start[0] , start[1] , goal[0] , goal[1]))
    heapq.heappush(q , (d[start][2] + d[start][3] , counter_queue , start))
    
    ans = False                         #this is to keep track wether the solution is found or not
    counter = 0
    while len(q) > 0 and ans == False:
        print("Number of steps :", counter)
        dist , waste , current = heapq.heappop(q)
        x = current[0]
        y = current[1]
        if (current == goal):
            ans = True
            break
        
        #print(counter , current)
        temp = d[current][2] + d[current][3]
        if (dist > temp):
            continue
        
        explored.add((current))
        counter+=1
        #print(current)
        if (isValid(x , y-1) and not grid[x][y-1] == 1 and (x , y-1) not in explored ):
            d[(x , y-1)] = (current , "left" , d[current][2] + 1, h_euclidean(x , y-1 , goal[0] , goal[1]))
            counter_queue += 1
            heapq.heappush(q , (d[(x,y-1)][2] + d[(x , y-1)][3] , counter_queue , (x , y-1)))
            
        if (isValid(x , y+1) and not grid[x][y+1] == 1 and (x , y+1) not in explored ):
            d[(x , y+1)] = (current , "right" , d[current][2] + 1, h_euclidean(x , y+1 , goal[0] , goal[1]))
            counter_queue += 1
            heapq.heappush(q , (d[(x,y+1)][2] + d[(x , y+1)][3] , counter_queue , (x , y+1)))
        
        if (isValid(x-1 , y) and not grid[x-1][y] == 1 and (x-1 , y) not in explored ):
            d[(x-1 , y)] = (current , "up" , d[current][2] + 1, h_euclidean(x-1 , y , goal[0] , goal[1]))
            counter_queue += 1
            heapq.heappush(q , (d[(x-1,y)][2] + d[(x-1 , y)][3] , counter_queue , (x-1 , y)))
        
        if (isValid(x+1 , y) and not grid[x+1][y] == 1 and (x+1 , y) not in explored ):
            d[(x+1 , y)] = (current , "down" , d[current][2] + 1, h_euclidean(x+1 , y , goal[0] , goal[1]))
            counter_queue += 1
            heapq.heappush(q , (d[(x+1,y)][2] + d[(x+1 , y)][3] , counter_queue , (x+1 , y)))
            
        if (isValid(x-1 , y-1) and not grid[x-1][y-1] == 1 and (x-1 , y-1) not in explored ):
            d[(x-1 , y-1)] = (current , "up left" , d[current][2] + 1, h_euclidean(x-1 , y-1 , goal[0] , goal[1]))
            counter_queue += 1
            heapq.heappush(q , (d[(x-1,y-1)][2] + d[(x-1 , y-1)][3] , counter_queue , (x-1 , y-1)))
            
        if (isValid(x-1 , y+1) and not grid[x-1][y+1] == 1 and (x-1 , y+1) not in explored ):
            d[(x-1 , y+1)] = (current , "up right" , d[current][2] + 1, h_euclidean(x-1 , y+1 , goal[0] , goal[1]))
            counter_queue += 1
            heapq.heappush(q , (d[(x-1,y+1)][2] + d[(x-1 , y+1)][3] , counter_queue , (x-1 , y+1)))
            
        if (isValid(x+1 , y-1) and not grid[x+1][y-1] == 1 and (x+1 , y-1) not in explored ):
            d[(x+1 , y-1)] = (current , "down left" , d[current][2] + 1, h_euclidean(x+1 , y-1 , goal[0] , goal[1]))
            counter_queue += 1
            heapq.heappush(q , (d[(x+1,y-1)][2] + d[(x+1 , y-1)][3] , counter_queue , (x+1 , y-1)))
            
            
        if (isValid(x+1 , y+1) and not grid[x+1][y+1] == 1 and (x+1 , y+1) not in explored ):
            d[(x+1 , y+1)] = (current , "down right" , d[current][2] + 1, h_euclidean(x+1 , y+1 , goal[0] , goal[1]))
            counter_queue += 1
            heapq.heappush(q , (d[(x+1,y+1)][2] + d[(x+1 , y+1)][3] , counter_queue , (x+1 , y+1)))         
    
    #this is to print the path
    if (ans == False):
        print("Solution not found")
        return 
    

    path = []
    path_name = []
    current = goal
    #print(d)
    #print(d[current])
    
    
    while (not current == start):
        path.insert(0 , current)
        path_name.insert(0 , d[current][1])
        current = d[current][0]
        
    
    path.insert(0 , start)    
    for i , j in zip(path , path_name):
        print(i , j)
        
    print(goal)
    
     

In [55]:
heuristic2()

(0, 0)
(0, 5)
[[0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0.]
 [1. 0. 0. 1. 0. 0.]
 [1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
Number of steps : 0
Number of steps : 1
Number of steps : 2
Number of steps : 3
Number of steps : 4
Number of steps : 5
Number of steps : 6
(0, 0) down
(1, 0) down right
(2, 1) up right
(1, 2) up right
(0, 3) down right
(1, 4) up right
(0, 5)
